### ISSUE TITLE
Request Support from different compiler versions

### ISSUE THREAD

**Issue by teraflops-droid** [Ratimon/solid-grinder#4]
Now, it only supports for solidity version 0.8.x, but sometimes it is required to revert back older versions for security concern. Personally, I suggest to add at least from 0.7.x

**Comment by Ratimon** [comment]
I agreed!!  I will put this in the next minor version. Should be released next month.

**Comment by teraflops-droid** [comment]
Thank you.

**Comment by Ratimon** [comment]
@teraflops-droid I have released new version to support solidity versions and updated the doc . Now it only support 0.7.6. Just add  : `--compiler-version 'solc_0_8'` following your command like :


`yarn solid-grinder gen-decoder --source 'contracts/solc_0_8/examples/uniswapv2/UniswapV2Router02.sol' --output 'contracts/solc_0_8/examples/uniswapv2' --contract-name 'UniswapV2Router02' --function-name 'addLiquidity' --arg-bits '24 24 96 96 96 96 24 40' --compiler-version 'solc_0_8'`

**Comment by Ratimon** [comment]
Marked as closed
